# Generated by Django 4.2.16 on 2024-11-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=32)),
                ("email", models.TextField(max_length=32)),
                ("phone", models.TextField(max_length=32)),
                ("is_favorite", models.BooleanField()),
            ],
        ),
    ]
